version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: auto-gsql-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auto_gsql_be
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    container_name: auto-gsql-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: auto-gsql-qdrant
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334

volumes:
  mysql_data:
  redis_data:
  qdrant_data:
